name: projec
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  pin_code_fields: ^7.4.0
  # Firebase dependencies
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true